I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6, in script
    init python:
  File "game/script.rpy", line 6, in script
    init python:
  File "game/script.rpy", line 10, in <module>
    out = check_output(["ntpq", "-p"])
OSError: [Errno 2] No such file or directory

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/moemen/gradproj/RenPy/renpy-7.4.11-sdk/renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "/home/moemen/gradproj/RenPy/renpy-7.4.11-sdk/renpy/main.py", line 560, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 6, in script
    init python:
  File "game/script.rpy", line 6, in script
    init python:
  File "/home/moemen/gradproj/RenPy/renpy-7.4.11-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/moemen/gradproj/RenPy/renpy-7.4.11-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 10, in <module>
    out = check_output(["ntpq", "-p"])
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/subprocess.py", line 217, in check_output
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/subprocess.py", line 325, in __init__
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/subprocess.py", line 978, in _execute_child
OSError: [Errno 2] No such file or directory

Linux-5.4.0-100-generic-x86_64-with-debian-bullseye-sid
Ren'Py 7.4.11.2266
RenPyTest 1.0
Mon Mar  7 19:09:00 2022
